### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by os400** [flecmart/keep2todoist#1]
Thanks, this was really useful. I had to adapt it so a 'OK Google, add a note to buy milk' was pulled as a note (rather than a list) and put in todoist as 'buy milk today', I also changed the keep note's title to 'Already synced' and appended a date to the text and then archived it. 
I don't use 'keep' for anything else so it works well in pulling over all single notes, but I'd ideally I'd like 'OK Google add a note' to make a distinction (set a title or label) so they are easier to find for someone who uses Keep for other reasons. 
Your way of using items would have been good except 'OK Google, add a note' doesn't seem to itemize Keep notes...

**Comment by flecmart** [comment]
If you want to keep Google keep clean: this still works for archived lists/notes.
