### ISSUE TITLE
gkeepapi 0.15.1

### ISSUE THREAD

**Issue by os400** [flecmart/keep2todoist#90]
Hi, I'm getting a parse error described here:
https://github.com/kiwiz/gkeepapi/issues/155

```
2024-12-11 09:08:04 app-INFO: transfering Shopping list from keep to todoist
keep2todoist-1  | Traceback (most recent call last):
keep2todoist-1  |   File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 214, in load
keep2todoist-1  |     self._load(raw)
keep2todoist-1  |   File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 295, in _load
keep2todoist-1  |     self._description = raw['webLink']['description']
keep2todoist-1  |                         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
keep2todoist-1  | KeyError: 'description'
```

I've been trying to find the culprit keep note(s) created by google assistant or 'gemini' but haven't stopped the error yet. 

The suggested solution is to upgrade gkeepapi from 0.14 to 0.15.1, but I'm not sure how to do that in a docker image.

**Comment by flecmart** [comment]
Hey,

reading through the issue you linked I remember that I had the same problemes when google keeps notes were migrated in the past. Can you try deleting and recreating the notes on google keeps side and test if that works? For me the setup with the older gkeepapi still works. 

I did not upgrade yet, because authentication will be more complicated with the new dependencies and I do not have a lot of spare time right now, but eventually I will look into it.

**Comment by os400** [comment]
Oh btw, I did delete all the 'To-Do' notes (and variants of to-do), and changed the config.yaml to ignore them all but came to the conclusion the 'description' was missing on a totally unrelated note.

**Comment by flecmart** [comment]
From your logs it I can see that the keep list `Shopping list` is erroring. Can you delete and recreate that?

**Comment by flecmart** [comment]
The migrated lists with the gemini icon... are they still in the google keeps trash? Try to remove them. Meanwhile let me check if I can quickly put up a version with the alternative authentication flow and new dependencies the next days

**Comment by os400** [comment]
Oh you star, thankyou for making me check - no the 'Gemini' one was still in the bin... I assumed 'archive' was bin and 'delete' was delete, I didn't think to check if there was a 'check bin' option. I've removed it and all is good again:
```
2024-12-11 13:08:15 app-INFO: Successfully authenticated with token 👍
keep2todoist-1  | 2024-12-11 13:08:15 app-INFO: start scheduler
keep2todoist-1  | 2024-12-11 13:08:15 app-INFO: transfering TestList list from keep to todoist
keep2todoist-1  | 2024-12-11 13:08:23 app-INFO: 	-> First item
keep2todoist-1  | 2024-12-11 13:08:24 app-INFO: 	-> Second item
```
If the 0.15.1 authentication is a problem then I'm happy to stick with the working 0.14... I have no idea why my phone suddenly created a separate, 'gemini' note but I know to look out for it now.
 
I doubt there is an option to ignore notes in the bin/archive, but if there is then that strikes me as a more useful change for clots like me.

Either way, thanks for your help.

**Comment by flecmart** [comment]
nice, then I close this and can wait a little longer with the version bumps for the api... glad to help :-)
